---
title: "Suggested timeline"
output:
  html_document: default
  pdf_document: default
date: "version `r format(Sys.time(), '%B %d, %Y')`"
subtitle: Statistical models in R
---

* 5 min: Intro to workshop and data; Setup
* 15 min: Experimental design

* 10 min: ANOVA
* 10 min: Fruit fly data 
* 15 min: 1-way ANOVA with 2 groups
* 10 min: Exercise

* 15 min: > 2 groups ANOVA
* 20 min: 2-way ANOVA +/- interaction
* 10 min: Exercise

* __End day 1 for 3 x 2-hour workshop__

* 5 min: gapminder data
* 10 min: Linear models
* 10 min: Simple linear regression
* 10 min: Residuals
* 10 min: Exercise

* 10 min: Cautions!

* __End day 1 for 2 x 3-hour workshop__

* 15 min: Multiple linear regression
* 10 min: Exercise (transformation)

* 15 min: log and polynomial transformations
* 10 min: Exercise (as homework if needed)
* 10 min: Interactions and ANCOVA

* __End day 2 for 3 x 2-hour workshop__

* 20 min: Linear mixed effects model
* 10 min: Exercise

* 20 min: General linear model (GLM)
* 15 min: Binomial GLM (homework exercise)

* 10 min: Poisson GLM
* 10 min: Exercise

* 15 min: Negative binomial
* 10 min: Exercise

* __End of workshop__